name: Build terminal-notifier
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select --switch /Applications/Xcode.app
    - name: List available schemes
      run: xcodebuild -list -project "Terminal Notifier.xcodeproj"
    - name: Build terminal-notifier
      run: |
        xcodebuild -project "Terminal Notifier.xcodeproj" -scheme "Terminal Notifier" -configuration Release -derivedDataPath ./DerivedData MACOSX_DEPLOYMENT_TARGET=10.13 clean build
    - name: Package artifact
      run: |
        cd DerivedData/Build/Products/Release
        zip -r ../../../terminal-notifier.zip terminal-notifier.app
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: terminal-notifier
        path: terminal-notifier.zip
