name: Build terminal-notifier
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Xcode dependencies
      run: |
        sudo xcode-select --install || true
    - name: Build terminal-notifier
      run: |
        make
    - name: Package artifact
      run: |
        zip -r terminal-notifier.zip terminal-notifier.app
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: terminal-notifier
        path: terminal-notifier.zip
